import Common from "./common.js";

class Register extends Common
{
    constructor()
    {
        super()
        this.$fname=()=>$(`//input[@placeholder="First Name"]`)
        this.$lname=()=>$(`//input[@placeholder="Last Name"]`)
        this.$address=()=>$(`//textarea[@ng-model="Adress"]`)
        this.$email=()=>$(`//input[@ng-model="EmailAdress"]`)
        this.$phone=()=>$(`//input[@ng-model="Phone"]`)
        this.$radiobtn=()=>$(`//input[@type="radio" and @value="FeMale"]`)
        this.$movies=()=>$(`//input[@id="checkbox2"]`)
        this.$hockey=()=>$(`//input[@id="checkbox3"]`)
        this.$langdropdown=()=>$(`//multi-select/div[@id="msdd"]`)
        this.$lang=()=>$(`//a[text()='English']`)
        this.$langlabel=()=>$(`//label[text()='Languages']`)
        this.$skilldropdown=()=>$(`//select[@id="Skills"]`)
        this.$skill=()=>$(`//select[@id="Skills"]/option[@value="Javascript"]`)
        this.$country=()=>$(`//span[@id="select2-country-container"]/parent::span`)
        this.$search=()=>$(`//input[@class="select2-search__field"]`)
        this.$countryvalue=()=>$(`//li[@class="select2-results__option select2-results__option--highlighted"]`)
        this.$yearbox=()=>$(`//select[@id="yearbox"]`)
        this.$year=()=>$(`//select[@id="yearbox"]/option[text()='2000']`)
        this.$monthbox=()=>$(`//select[@ng-model="monthbox"]`)
        this.$month=()=>$(`//select[@ng-model="monthbox"]/option[text()='March']`)
        this.$daybox=()=>$(`//select[@ng-model="daybox"]`)
        this.$day=()=>$(`//select[@ng-model="daybox"]/option[text()='22']`)
        this.$password=()=>$(`//input[@id="firstpassword"]`)
        this.$cpassword=()=>$(`//input[@id="secondpassword"]`)
        this.$upload=()=>$(`//input[@id="imagesrc"]`)
        this.$submitbtn=()=>$(`//button[@id="submitbtn"]`)
    }
    async register()
    {
        await this.$fname().setValue('David')
        await this.$lname().setValue('Jones')
        await this.$address().setValue('New York')
        await this.$email().setValue('david@gmail.com')
        await this.$phone().setValue('1234567890')
        await this.$radiobtn().click()
        await this.$movies().click()
        await this.$hockey().click()
        await this.$langdropdown().click()
        await this.$lang().click()
        await this.$langlabel().click()
        await this.$skilldropdown().click()
        await this.$skill().click()
        await this.$country().click()
        await this.$search().setValue('India')
        await this.$countryvalue().click()
        await this.$yearbox().click()
        await this.$year().click()
        await this.$monthbox().click()
        await this.$month().click()
        await this.$daybox().click()
        await this.$day().click()
        await this.$password().setValue('david123')
        await this.$cpassword().setValue('david123')
    }
    async upload()
    {
        const filepath='uploads/sample.txt'
        const relativefilepath=await browser.uploadFile(filepath)
        await this.$upload().setValue(relativefilepath)
        await this.$submitbtn().click()
     //   await this.$upload().click()
    }
}
export default new Register()